doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
            host: 'localhost'  # Adresse de votre serveur MySQL
        port: 3306        # Port MySQL (par défaut)
        dbname: projet_annuel  # Nom de votre base de données
        user: root       # Utilisateur MySQL
        password: 'votre_mot_de_passe_mysql'  # Mot de passe MySQL


    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
