controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

# download_existing_file:
#     path: '/download/{id}'
#     controller: App\Controller\FileController::downloadFile

# config/routes.yaml
download_existing_file:
    path: '/download/{id}'
    controller: 'App\Controller\FileController::downloadFile'

# config/routes.yaml

user_delete_confirm:
    path: '/utilisateur/supprimer'
    controller: 'App\Controller\UserDeleteController::confirmDelete'
    methods: ['GET']

user_delete_execute:
    path: '/utilisateur/supprimer/execute'
    controller: 'App\Controller\UserDeleteController::deleteUser'
    methods: ['POST']

# admin_liste_clients:
#     path: /admin/liste-clients
#     controller: App\Controller\AdminController::listeClients

# admin_tableau_de_bord:
#     path: /admin/tableau-de-bord
#     controller: App\Controller\AdminController::tableauDeBord

# doctrine:
#     dbal:
#         driver: 'pdo_mysql'
#         server_version: '5.7'
#         charset: utf8mb4
#         default_table_options:
#             charset: utf8mb4
#             collate: utf8mb4_unicode_ci
#         url: '%env(resolve:DATABASE_URL="mysql://root:@127.0.0.1:3306/projet_annuel?serverVersion=5.7")%' 
        # Vous pouvez également spécifier directement la configuration ici
